### ISSUE TITLE
Private Organization repositories

### ISSUE THREAD

**Issue by aammd** [traitecoevo/datastorr#14]
filing this here because one cannot place issues on a fork.. it seems like there is a problem when fetching a private (but not a public) Organization repository. Perhaps something around [this line](https://github.com/richfitz/datastorr/blob/master/R/github_api.R#L58) or something similar in the github API functions.

**Comment by aammd** [comment]
for example (`thedat` here means info for a private, organization repo):

```r
github_release_versions(thedat, local = FALSE)
character(0)
```

**Comment by aammd** [comment]
This problem appears more subtle than I previously believed. If a repository is private then the version of a release can be accessed (by a user with a suitable `GITHUB_TOKEN`):

<img width="726" alt="image" src="https://cloud.githubusercontent.com/assets/1198242/21884774/f8e0c450-d8b4-11e6-940d-f2909f440782.png">

However the latest version cannot be read (or, oddly, cannot be _completely_ read):

<img width="877" alt="image" src="https://cloud.githubusercontent.com/assets/1198242/21884823/2e1abce8-d8b5-11e6-867b-0ed216a19ad3.png">

**Comment by richfitz** [comment]
Thanks - probably it's not passing the auth through for that function

Just back from NZ - please bump this if I don't look at it in the next week or so...

**Comment by richfitz** [comment]
Progress here on https://github.com/ropenscilabs/datastorr/tree/i14-private-repos

**Comment by wcornwell** [comment]
is this resolved?

**Comment by richfitz** [comment]
I think so
